/*
 * Name: Aisha Lalli
 * Date: 3/16/2021
 * Course: CST338 - Java
 * Module 2: Casino
 * Description: Class Assig2 has many static methods and main.
 *              Class ThreeStrings creates object for slot machine
 *              This program will create a slot machine where the user can bet 
 *              from 1-100 $. The results are generated by random using
 *              percentages for each slot occurrence. 
 */


import java.util.*;//scanner

public class Assig2
{
   private static int multiplier = 0; // This is used to calculate winnings and
                                     //in getPayMultiplier()
   
   //Prompt user,validate amount,repeat till correct, return legal int amount
   public static int getBet()
   {
      Scanner keyboard = new Scanner(System.in);
      int betAmount = 0;
      
      // repeat till range btw 0-100
      do
      {
         System.out.println("\n");
         System.out.print("How much would you like to bet (1 - 100) or 0 to" +
      " quit? ");
         betAmount = keyboard.nextInt();
      }while (betAmount < 0 || betAmount > 100); 
      
      return betAmount;
   }
   
   //instantiate object, fill with 3 random generated strings, use randString()
   //store date in a ThreeString object, Return the ThreeString object
   public static ThreeString pull()
   {
      ThreeString pullString = new ThreeString();
      
      pullString.setString1(randString()); // send randString to ThreeString
      pullString.setString2(randString()); // setString methods respectively
      pullString.setString3(randString());
      
      return (pullString);
   }
   
   //produce random strings based on percentages,return a single random string
   //Math.random() gives a number between [0,1)
   private static String randString()
   {
      String str = "";
      if (Math.random() < 0.50) //50%
      {
         str = "Space";
      }
      else if (Math.random() < 0.75) //25% => 50+25 = 75/100 = 0.75
      {
         str = "Cherries";
      }
      else if (Math.random() < 0.875) // 12.5%
      {
         str = "BAR";
      }
      else if (Math.random()< 1.0) // 12.5%
      {
         str = "7";
      }
      return str;
   }
   
   //takes in the ThreeString object and returns the multiplier based
   //on the order of strings Cherries,7,BAR and space.
   public static int getPayMultiplier(ThreeString thePull)
   {  
      if(thePull.getString1().equals("Cherries") && 
            !thePull.getString2().equals("Cherries"))
      {
         multiplier = 5;
      }
      else if(thePull.getString1().equals("Cherries") && 
            thePull.getString2().equals("Cherries") && 
            !thePull.getString3().equals("Cherries"))
      {
         multiplier = 15;
      }
      else if(thePull.getString1().equals("Cherries") && 
            thePull.getString2().equals("Cherries") && 
            thePull.getString3().equals("Cherries"))
      {
         multiplier = 30;
      }
      else if(thePull.getString1().equals("BAR") && 
            thePull.getString2().equals("BAR") && 
            thePull.getString3().equals("BAR"))
      {
         multiplier = 50;
      }
      else if(thePull.getString1().equals("7") && 
            thePull.getString2().equals("7") && 
            thePull.getString3().equals("7"))
      {
         multiplier = 100;
      }
      else // if ThreeString object strings are empty
      {
         multiplier = 0;
      }
      return (multiplier);
   }
   
   //takes in the winning amounts(bet x multiplier)
   //gets 3 strings out of ThreeString object
   //display string using toString() from ThreeString class and print out
   //win or loss by checking if the winnings greater than 0
   public static void display(ThreeString thePull, int winnings)
   {
      System.out.println(thePull.toString());
      System.out.println("-----------------------------------");
      if(winnings != 0)
      {
         System.out.println("Congrats you won: " + winnings);
      }
      else
      {
         System.out.println("Sorry, you lose");
      }
   }
   
   //This is were the main actions take pace using both classes
   public static void main(String[] args)
   {
      //placed the var. below out of the loop to be used throughout main
      //no need to re-create throughout loop 
      int userBet = 0; 
      int thisPullWinning = 0;// holds individual run winnings to be saved
      
      //program keeps running till user enters 0, a break statement within end
      //program when 
      do
      {
         userBet = Assig2.getBet();
         
         ThreeString thisPlayObject = null; 
         thisPlayObject = Assig2.pull(); // ThreeString object get user bet
         if (userBet != 0) // user does not want to exit
         {
            System.out.println("whirrrr .... and your pull is ... ");
            System.out.println("-----------------------------------");
            
            //get multiplier to calculate thisPullWinnings
            multiplier = Assig2.getPayMultiplier(thisPlayObject);
            thisPullWinning = userBet * multiplier;
            
            //display random strings and user winnings for the current round
            Assig2.display(thisPlayObject, thisPullWinning);
            
            
            //the next 2 if statements are for when the user wants to play
            //the call to saveWinnings will save amount won in array
            //pullWinnings from ThreeString class
            //will return true when numPulls < MAX_PULLS 
            //will return false if MAX_PULLS -1 reached => userBet=0 to exit
            if(!thisPlayObject.saveWinnings(thisPullWinning))
            {
               userBet = 0;
            }
            
            //When MAX_PULLS is reached by numPulls give results and break out
            //of do while loop
            if (ThreeString.numPulls == ThreeString.MAX_PULLS)
            { 
              System.out.println("\n" + thisPlayObject.toStringWinnings());
              break;
            }
         }
         //the user no longer wants to play 
         if (userBet == 0 )
         {
           System.out.println(thisPlayObject.toStringWinnings());
         }
         
      //decide to play again or exit  
      }while (userBet != 0);
      
      System.out.println("Come Back Soon!");
   }
}

class ThreeString
{
   private String string1, string2, string3;
   //the following are static and can be changed by different methods
   public static final int MAX_LEN = 20; //max length of string
   public static final int MAX_PULLS = 40;
   static int[]pullWinnings = new int[MAX_PULLS];
   public static int numPulls = 0;
 
   
   ThreeString() // constructor
   {
      string1 = "";
      string2 = "";
      string3 = "";
   }
   
   private boolean validString(String str) // determine if string is legal
   {
      if (str != null && str.length() <= MAX_LEN) //string is not empty or full
      {
         return (true);
      }
      else
      {
         return (false);
      } 
   }
   
   //receive string and set it in the object ThreeString, return true if saved
   public boolean setString1(String str)
   {
      if(validString(str)) //check if string is valid then input string 
      {
         string1= str;
         return (true);
      }
      else
      {
         System.out.println("This is not Legal");
         return (false);
      }
   }
   
   public boolean setString2(String str)
   {
      if(validString(str))
      {
         string2= str;
         return (true);
      }
      else
      {
         System.out.println("This is not Legal");
         return (false);
      }
   }
   public boolean setString3(String str)
   {
      if(validString(str))
      {
         string3= str;
         return (true);
      }
      else
      {
         System.out.println("This is not Legal");
         return (false);
      }
   }
  
   //the following methods return the contents of the string variables if needed
   public String getString1()
   {
      return string1;
   }
   
   public String getString2()
   {
      return string2;
   }
   
   public String getString3()
   {
      return string3;
   }
   
   //returns a string sentence of the results of pull
   public String toString()
   {
      String sentence = string1 + " " + string2 +
            " " + string3;
      return (sentence);
   }
   
   //receive the winning $$$ save them in array, return true when done
   //true if not limit reached
   //false if limit reached
   //numPulls increments in both true and false
   public boolean saveWinnings(int winnings)
   {
      //pulls reach 38=MAX_PULLS-1 and increments to 39
      if(numPulls < MAX_PULLS-1)
      {
         pullWinnings[numPulls] = winnings;
         numPulls++;
      
         return (true);
      }
      //pulls reach 39=MAX_PULLS-1 and increments to 40
      //if false main stops playing game
      else 
      {  
         pullWinnings[numPulls] = winnings;
         numPulls++;
         
         return (false);
      }
   }
   
   //use loop to get values out, put them in totalWinnings,
   //return string sentence including all individual wins and total $$ wins
   public String toStringWinnings()
   {
      String sentence = "Your individual winnings were: ";
      int totalWinnings = 0;
      
      //go through array get total $$ and put them in a sentence
      for(int i = 0; i<numPulls; i++)
      {
         totalWinnings = totalWinnings +  pullWinnings[i];
         sentence = sentence + " " + pullWinnings[i];
         
      }
      //player exits before any game is played
      if (numPulls == 0)
      {
         sentence = sentence + " You had no wins.";
      }
      sentence = sentence + "\nYour total winnings were: $" + totalWinnings;
      
      return (sentence);
   }
   
}

/*--------------------------output test 1---------------------------------
 * How much would you like to bet (1 - 100) or 0 to quit? 0
Your individual winnings were:  You had no wins.
Your total winnings were: $0
Come Back Soon!
--------------------------------------------------------------------------
-----------------------------output till max limit reached----------------
 * 

How much would you like to bet (1 - 100) or 0 to quit? 1
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 2
whirrrr .... and your pull is ... 
-----------------------------------
Space Cherries Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 3
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 4
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space Space
-----------------------------------
Congrats you won: 20


How much would you like to bet (1 - 100) or 0 to quit? 5
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Cherries Cherries
-----------------------------------
Congrats you won: 150


How much would you like to bet (1 - 100) or 0 to quit? 6
whirrrr .... and your pull is ... 
-----------------------------------
Space Cherries Cherries
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 7
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space BAR
-----------------------------------
Congrats you won: 35


How much would you like to bet (1 - 100) or 0 to quit? 8
whirrrr .... and your pull is ... 
-----------------------------------
Space Cherries Cherries
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 9
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space BAR
-----------------------------------
Congrats you won: 45


How much would you like to bet (1 - 100) or 0 to quit? 11
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Cherries
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 22
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Cherries Cherries
-----------------------------------
Congrats you won: 660


How much would you like to bet (1 - 100) or 0 to quit? 33
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 44
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space Cherries
-----------------------------------
Congrats you won: 220


How much would you like to bet (1 - 100) or 0 to quit? 55
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space Cherries
-----------------------------------
Congrats you won: 275


How much would you like to bet (1 - 100) or 0 to quit? 66
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Cherries Space
-----------------------------------
Congrats you won: 990


How much would you like to bet (1 - 100) or 0 to quit? 77
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 88
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Cherries
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 99
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 100
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 123


How much would you like to bet (1 - 100) or 0 to quit? 300


How much would you like to bet (1 - 100) or 0 to quit? 100
whirrrr .... and your pull is ... 
-----------------------------------
Space Cherries Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 12
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Cherries Space
-----------------------------------
Congrats you won: 180


How much would you like to bet (1 - 100) or 0 to quit? 11
whirrrr .... and your pull is ... 
-----------------------------------
Space BAR Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 22
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 23
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space BAR
-----------------------------------
Congrats you won: 115


How much would you like to bet (1 - 100) or 0 to quit? 14
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space Cherries
-----------------------------------
Congrats you won: 70


How much would you like to bet (1 - 100) or 0 to quit? 43
whirrrr .... and your pull is ... 
-----------------------------------
Space BAR Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 7
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 65
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 46
whirrrr .... and your pull is ... 
-----------------------------------
7 Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 78
whirrrr .... and your pull is ... 
-----------------------------------
BAR Cherries Cherries
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 65
whirrrr .... and your pull is ... 
-----------------------------------
Space Cherries Cherries
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 43
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 66
whirrrr .... and your pull is ... 
-----------------------------------
Cherries 7 BAR
-----------------------------------
Congrats you won: 330


How much would you like to bet (1 - 100) or 0 to quit? 88
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 66
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space Space
-----------------------------------
Congrats you won: 330


How much would you like to bet (1 - 100) or 0 to quit? 55
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 44
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Cherries
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 33
whirrrr .... and your pull is ... 
-----------------------------------
Space Space Cherries
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 55
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space Cherries
-----------------------------------
Congrats you won: 275


How much would you like to bet (1 - 100) or 0 to quit? 77
whirrrr .... and your pull is ... 
-----------------------------------
BAR Cherries Cherries
-----------------------------------
Sorry, you lose

Your individual winnings were:  0 0 0 20 150 0 35 0 45 0 660 0 220 275 990 0 0 0 0 0 180 0 0 115 70 0 0 0 0 0 0 0 330 0 330 0 0 0 275 0
Your total winnings were: $3695
Come Back Soon!
------------------------------------------------------------------------------
----------------------Output till user exits-----------------------------------


How much would you like to bet (1 - 100) or 0 to quit? 200


How much would you like to bet (1 - 100) or 0 to quit? 100
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Cherries Space
-----------------------------------
Congrats you won: 1500


How much would you like to bet (1 - 100) or 0 to quit? 46
whirrrr .... and your pull is ... 
-----------------------------------
Cherries Space Space
-----------------------------------
Congrats you won: 230


How much would you like to bet (1 - 100) or 0 to quit? 5
whirrrr .... and your pull is ... 
-----------------------------------
Space Space BAR
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 44
whirrrr .... and your pull is ... 
-----------------------------------
BAR Cherries Space
-----------------------------------
Sorry, you lose


How much would you like to bet (1 - 100) or 0 to quit? 0
Your individual winnings were:  1500 230 0 0
Your total winnings were: $1730
Come Back Soon!
-----------------------------------------------------------------------------
-----------------------------------------------------------------------------
 */
